color: green
description: null
fieldLayouts:
  b6eb94bb-24fc-49e2-b2ac-6366f7421712:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-17T07:46:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cda21870-0257-401e-b49e-8c4988c4289f # Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55ae061c-156a-43eb-90cf-68400240776c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-17T11:37:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce705e3c-b417-4928-a23c-47761737f752 # Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18df39c6-f3a6-48ed-b599-4aaa0f5a6664
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a34dc2a-e8ab-4a5d-a12b-9c05d6efa567
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-29T13:28:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eadcc8ce-5a2b-4dea-bc4c-a4581336aec7 # Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08ce1df3-39d1-47e8-a30f-f2e33d51c443
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: e23a2428-f60b-4cb8-88a3-dc535800e332
        userCondition: null
handle: bodyNews
hasTitleField: false
icon: null
name: 'Body: news'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
