columnSuffix: null
handle: commonSpacing
instructions: null
name: Spacing
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - default
        -
          - value
          - default
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - small
        -
          - value
          - small
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'small top, default bottom'
        -
          - value
          - smallTopDefaultBottom
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'small bottom, default top'
        -
          - value
          - smallBottomDefaultTop
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
