columnSuffix: null
handle: commonColor
instructions: null
name: Color
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - green
        -
          - value
          - green
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - peach
        -
          - value
          - peach
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
