defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fd7abea2-fcbf-4b1b-a85f-618a52111a44 # News body
handle: news
maxAuthors: 1
minAuthors: 1
name: news
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  e1f2a3b4-5c6d-7e8f-9a0b-1c2d3e4f5a6b:
    enabledByDefault: true
    hasUrls: true
    template: news/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
